spring:
  application:
    name: green.search.api.ch.gov.uk
  jackson:
    mapper:
      sort-properties-alphabetically: false
server:
  servlet:
    context-path: /green
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /search
      path-mapping:
        health: healthcheck
  endpoint:
    health:
      enabled: true
      show-details: never
